### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by noahkaefer** [HakaiInstitute/kelp-o-matic#121]
Hello beginner here,

I'm not sure where I am going wrong. I followed the instructions and when the segmentation process completes it outputs a completely black image.  Any suggestions would be very much appreciated! I attached the code and the image I used (cropped so it's not so big).

![test3](https://github.com/user-attachments/assets/3a5c69a9-ab7a-477e-951c-4658304971e9)

![kelp_o_matic_code](https://github.com/user-attachments/assets/0af5111e-4208-41b0-9994-f27366ff47a1)

**Comment by tayden** [comment]
Hi @noahkaefer, did you try to visualize the output by classifying the pixel values? The output values are all going to be 0 or 1 (for kelp presence detection) or 0,2,3 (for species segmentation). So, because all the values are close to black, it will look black unless you change the visualization settings.

Otherwise, the image looks good. So I'd expect it to work. Let me know if that doesn't solve it.

**Comment by tayden** [comment]
![image](https://github.com/user-attachments/assets/f18b144a-d313-4b84-a6e2-46614d5dae6b)

**Comment by noahkaefer** [comment]
Hi Taylor,

Yes, this fixed my problem! Thank you!
